apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath  # Usar o mesmo nome visto no kubectl get storageclass
  resources:
    requests:
      storage: 5Gi  # Suficiente para dashboards e configurações