apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Usa o StorageClass padrão do cluster
  resources:
    requests:
      storage: 10Gi