apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Tamanho ajustável
  storageClassName: standard  # Usa o StorageClass padrão do cluster