apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath  # Usar o StorageClass real
  resources:
    requests:
      storage: 1Gi