apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
data:
  locustfile.py: |
    from locust import HttpUser, task, between
    import random  # Para seleção aleatória de prompts

    # Lista de prompts variados para teste realista
    PROMPTS = [
        "Um dragão que cospe flores",
        "Uma aventura no espaço sideral",
        "Um misterioso castelo assombrado",
        "Uma inteligência artificial que ganha consciência",
        "Uma jornada através do tempo"
    ]

    class ApiUser(HttpUser):
        wait_time = between(1, 3)

        @task
        def generate_story(self):
            # Seleciona um prompt aleatório
            prompt = random.choice(PROMPTS)
            
            # Envia a requisição para o endpoint correto (porta 5000)
            self.client.post(
                url="http://inference-service:6000/generate",  # Endpoint corrigido
                json={
                    "text": prompt,  # Chave corrigida (de "prompt" para "text")
                    "size": 100,
                    "temperature": 0.7
                },
                headers={"Content-Type": "application/json"}  # Header necessário
            )