apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust
spec:
  type: ClusterIP
  selector:
    app: locust
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  

