apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: default
data:
  config.yaml: |
    rules:
      - seriesQuery: 'http_requests_total{job="storIA"}'
        resources:
          overrides:
            namespace:
              resource: "namespace"
        name:
          matches: "^(.*)_total"
          as: "${1}_per_second"
        metricsQuery: 'sum(rate(http_requests_total{job="storIA"}[2m])) by (job)'
