apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meu-chart.fullname" . }}-inference  # Nome único
  namespace: {{ .Release.Namespace }}
  labels:
    app: inference
    {{- include "meu-chart.labels" . | nindent 4 }}  # Nome correto do template

spec:
  replicas: {{ .Values.inference.replicas }}
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
        {{- include "meu-chart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: inference
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: {{ .Values.inference.command | toYaml | nindent 12 }}
        ports:
        - containerPort: {{ .Values.inference.port }}
        resources:
          {{- toYaml .Values.inference.resources | nindent 12 }}
        volumeMounts:
          - name: storia-logs
            mountPath: {{ .Values.volumes.hostPath }}
      volumes:
        - name: storia-logs
          hostPath:
            path: {{ .Values.volumes.hostPath }}
            type: DirectoryOrCreate