apiVersion: v1
kind: Service
metadata:
  name: {{ include "meu-chart.fullname" . }}-inference-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meu-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: {{ .Values.inference.servicePort }}
      targetPort: {{ .Values.inference.port }}
  type: {{ .Values.inference.serviceType }}