services:
  # --- Aplicação (API) ---
  api:
    build:
      context: .  # Diretório do Dockerfile
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    networks:
      - monitoring-net
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: >
          container=api,project_name=storIA

  # --- Segunda Instância da Aplicação ---
  api2:
    build:
      context: .  # Diretório do Dockerfile
      dockerfile: Dockerfile
    container_name: api2
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    networks:
      - monitoring-net
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: >
          container=api2,project_name=storIA

  # --- NGINX como Balanceador de Carga ---
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Porta externa mapeada para o NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Monta a configuração do NGINX
    networks:
      - monitoring-net

  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitoring-net

  # --- Loki ---
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - monitoring-net
  
  # --- Promtail ---
  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../storIA/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - monitoring-net

volumes:
  grafana-data:

networks:
  monitoring-net:
    name: monitoring-net
    driver: bridge
