apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest # Redis Exporter para coletar métricas do Redis e expô-las ao Prometheus
        args:
          - "--redis.addr=redis:6379"
        ports:
        - containerPort: 9121