server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml  # Onde Promtail armazenará as posições dos logs

clients:
  - url: http://loki:3100/loki/api/v1/push  # URL do Loki (nome do serviço + porta)

scrape_configs:
  - job_name: storIA_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: storIA
          __path__: /var/log/storia.log  # Caminho dentro do container Promtail