auth_enabled: false

common:
  path_prefix: /tmp/loki  # Usado para evitar erro de "working_directory is empty"

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper  # Correto: 'boltdb-shipper' para indexação
      object_store: filesystem
      schema: v11  # Mantido como v11, pois v13 exige alterações mais complexas
      index:
        prefix: index_  # Mantido o valor correto, mas sem path_prefix aqui
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index  # Diretório para índice ativo
    cache_location: /tmp/loki/boltdb-cache  # Local de cache do índice
  filesystem:
    directory: /tmp/loki/chunks  # Local onde os chunks de log serão armazenados

limits_config:
  reject_old_samples: true  # Rejeitar amostras antigas
  reject_old_samples_max_age: 168h  # Limite para amostras de logs antigos
  allow_structured_metadata: false  # Desabilita metadata estruturada

compactor:
  working_directory: /tmp/loki/compactor  # Corrige o erro "working_directory is empty"

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # Mantém logs por 7 dias
