apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meu-chart.fullname" . }}-api  # Usar helper function
  namespace: {{ .Release.Namespace }}  # Adicionar namespace

spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: storia-logs
              mountPath: {{ .Values.volumes.hostPath }}
      volumes:
        - name: storia-logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storia-logs  # Usar PVC ao invés de hostPath