apiVersion: v1
kind: Service
metadata:
  name: {{ include "meu-chart.fullname" . }}-api-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: api-service
spec:
  selector:
    app: api-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
