apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "meu-chart.fullname" . }}-api-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-service
