apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        args:  # Adicione este bloco para especificar o arquivo de configuração
          - "-config.file=/etc/loki/loki.yml"  # Caminho absoluto
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - name: config
          mountPath: /etc/loki  # Diretório onde o arquivo será montado
        - name: storage
          mountPath: /tmp/loki
      volumes:
      - name: config
        configMap:
          name: loki-config
          defaultMode: 420  # Permissões de leitura para o arquivo (0644)
      - name: storage
        emptyDir: {}