apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment  # Nome da base!
spec:
  replicas: 1  
  template:
    spec:
      containers:
      - name: api  # Nome do container na base!
        env:
        # Variável nova para identificar o ambiente
        - name: ENVIRONMENT
          value: staging
        # Altere o host do Redis para o serviço no namespace staging
        - name: REDIS_HOST
          value: redis-service.staging.svc.cluster.local  # Nome do serviço Redis no staging
        # Ajuste de recursos para staging
        resources:
          requests:
            cpu: "100m"   # Reduzido
            memory: "256Mi"
          limits:
            cpu: "500m"   # Reduzido
            memory: "512Mi"