apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment  # Nome deve bater com o da base!
spec:
  replicas: 1 
  template:
    spec:
      containers:
      - name: redis
        # Ajuste de recursos (opcional para staging)
        resources:
          limits:
            cpu: "200m"    # Mantido igual à base
            memory: "256Mi"
        # Adicione variáveis de ambiente se necessário (ex: senha)
        env:
        - name: REDIS_PASSWORD
          value: "staging-password"