apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api
          image: api-service:latest 
          imagePullPolicy: Always               # Garante que a imagem mais recente seja puxada
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "2"
              memory: "512Mi"       # Aumentado de 256Mi para 512Mi
            limits:
              cpu: "4"
              memory: "1Gi"         # Aumentado de 512Mi para 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60        # Aumentado para dar mais tempo de inicialização
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3