apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference  # Certifique-se de que o selector bate com os labels do Deployment
  ports:
    - protocol: TCP
      port: 6000  # Porta do Service
      targetPort: 6000  # Porta do container
  type: ClusterIP