apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: api-service:latest  # imagem que contém o serviço de inferência
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "app.inference_service"]
        ports:
        - containerPort: 6000
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "3Gi"
            cpu: "2"
        volumeMounts:
          - name: storia-logs
            mountPath: /var/log/storIA
      volumes:
        - name: storia-logs
          hostPath:
            path: /var/log/storIA
            type: DirectoryOrCreate
