apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
      - name: wait-before-start
        image: busybox
        command: ["sleep", "30"]  # Espera 30 segundos antes de iniciar o pod

      containers:
      - name: worker
        image: api-service:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "app.worker"]
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
          - name: storia-logs
            mountPath: /var/log/storIA
      volumes:
        - name: storia-logs
          hostPath:
            path: /var/log/storIA
            type: DirectoryOrCreate
