apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:  # Credenciais via Secret
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana-auth  # Secret criado anteriormente
                key: GF_SECURITY_ADMIN_USER
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-auth
                key: GF_SECURITY_ADMIN_PASSWORD
        volumeMounts:
        - name: grafana-config  # ConfigMap com a fonte de dados do Loki
          mountPath: /etc/grafana/provisioning/datasources/loki-datasource.yaml
          subPath: loki-datasource.yaml
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config  # ConfigMap com o YAML do Loki