promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
  extraVolumes:
    - name: storia-logs
      persistentVolumeClaim:
        claimName: storia-logs
  extraVolumeMounts:
    - name: storia-logs
      mountPath: /var/log/storIA

loki:
  enabled: true
  config:
    existingSecret: ""     # Não está usando um secret existente
    config: |-
      auth_enabled: false

      common:
        path_prefix: /loki/data
        storage:
          filesystem:
            chunks_directory: /loki/data/chunks
            rules_directory: /loki/data/rules

      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
        chunk_idle_period: 30m
        chunk_target_size: 1536000  # 1.5MB

      schema_config:
        configs:
          - from: 2025-01-01
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h

      storage_config:
        boltdb_shipper:
          active_index_directory: /loki/data/index
          cache_location: /loki/data/boltdb-cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /loki/data/chunks

      limits_config:
        allow_structured_metadata: false
        reject_old_samples: false
        reject_old_samples_max_age: 168h
        retention_period: 720h
        retention_stream:
          - selector: '{job="storIA"}'
            priority: 1
            period: 720h

      compactor:
        working_directory: /loki/data/compactor
        compaction_interval: 10m

      table_manager:
        retention_deletes_enabled: true
        retention_period: 720h
