environment: staging

# Imagem local, sem mudar a base
image:
  repository: api-service
  tag: latest
  pullPolicy: IfNotPresent

# Sobrescrevendo apenas o que for diferente do default
api:
  replicas: 1
  redisHost: "storia-staging-redis-master"   # Se no template estiver usando .Values.api.redisHost
  redisPort: "6379"
  # Se quiser manter as resources do default, não precisa repetir

inference:
  replicas: 1
  # resources fica o do default, se não tiver mudança

worker:
  replicas: 1
  redisHost: "storia-staging-redis-master"   # Adicione esta linha
  redisPort: "6379"                         # Adicione esta linha
  command: ["python", "-m", "app.worker"]
  initContainer:
    image: "busybox"
    delay: "20"
# Caso você queira *explicitamente* outro PSC de volumes ou outro storage class no staging
storage:
  className: hostpath

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
