apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  # Configurações adicionais (ex: plugins, dashboards padrão)
  custom.ini: |-
    [plugins]
    allow_loading_unsigned_plugins = true

  # Datasource para Loki (opcional)
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100