apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  # O nome da chave DEVE ser "loki.yml" (igual ao nome do arquivo que o Loki espera)
  loki.yml: |-  
    auth_enabled: false

    common:
      path_prefix: /tmp/loki

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/boltdb-cache
      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      allow_structured_metadata: false

    compactor:
      working_directory: /tmp/loki/compactor

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h