apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yml: |-
    auth_enabled: false

    common:
      path_prefix: /loki/data
      storage:
        filesystem:
          chunks_directory: /loki/data/chunks
          rules_directory: /loki/data/rules

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_target_size: 1536000  # 1.5MB

    schema_config:
      configs:
        - from: 2025-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/data/index
        cache_location: /loki/data/boltdb-cache
      filesystem:
        directory: /loki/data/chunks

    limits_config:
      allow_structured_metadata: false  # Desabilita Structured Metadata
      reject_old_samples: false         # Permite logs com timestamps futuros
      reject_old_samples_max_age: 0
      retention_period: 720h
      retention_stream:
        - selector: '{job="storIA"}'
          priority: 1
          period: 720h

    compactor:
      working_directory: /loki/data/compactor
      compaction_interval: 10m

    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h  # Deve ser igual ao limits_config
