apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /var/log/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push  # Endpoint do Loki

    scrape_configs:
      - job_name: storIA_logs 
        static_configs:
          - targets: [localhost]
            labels:
              job: storIA
              logger: storIA_logger
              __path__: /var/log/storIA/*.log  # Caminho dos logs no container