apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: storIA-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: storIA
              __path__: /var/log/storIA/*.log
        pipeline_stages:
          - cri: {}  # Se os logs estiverem no formato CRI, esta etapa pode extrair metadados
