{{- if and .Values.grafana.persistence.enabled (not .Values.grafana.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "meu-chart.fullname" . }}-grafana-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size | default "10Gi" }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName | default "standard" | quote }}
{{- end }}
