apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.existingSecret | default "grafana-auth" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.admin.user | default "TAIL" | quote }}
  admin-password: {{ .Values.grafana.admin.password | default "TAIL123" | quote }}
