resources:
- api-service/api-service-deployment.yaml  # Caminho para o deployment da API
- api-service/api-service-service.yaml     # Serviço da API
- api-service/api-service-hpa.yaml         # Horizontal Pod Autoscaler da API
- api-service/inference-deployment.yaml    # Deployment do serviço de inferência
- api-service/inference-service.yaml       # Serviço do serviço de inferência
- api-service/worker-deployment.yaml       # Deployment do worker
- configmap/configmap.yaml                 # ConfigMap
- configmap/grafana-configmap.yaml         # ConfigMap do Grafana
- configmap/prometheus-configmap.yaml      # ConfigMap do Prometheus
- configmap/loki-configmap.yaml            # ConfigMap do Loki
- configmap/promtail-configmap.yaml        # ConfigMap do Promtail
- configmap/locust-configmap.yaml          # ConfigMap do Locust
- grafana/grafana-deployment.yaml          # Deployment do Grafana
- grafana/grafana-service.yaml             # Serviço do Grafana
- grafana/grafana-secrects.yaml            # Secret do Grafana
- ingress/ingress-app.yaml                 # Ingress da aplicação
- locust/locust-deployment.yaml            # Deployment do Locust
- locust/locust-service.yaml               # Serviço do Locust
- loki/loki-deployment.yaml                # Deployment do Loki
- loki/loki-service.yaml                   # Serviço do Loki
- monitoring/grafana-pvc.yaml              # PVC do Grafana
- monitoring/grafana-secret.yaml           # Secret do Grafana
- monitoring/loki-pvc.yaml                 # PVC do Loki
- monitoring/prometheus-pvc.yaml           # PVC do Prometheus
- prometheus/configmap-reader-role.yaml    # Role do ConfigMap Reader
- prometheus/extension-apiserver-authentication-reader.yaml # Role do Extension API Server Authentication Reader
- prometheus/prometheus-adapter-auth-reader.yaml # Role do Prometheus Adapter Auth Reader
- prometheus/prometheus-adapter-config.yaml # Config do Prometheus Adapter
- prometheus/prometheus-adapter-configmap-reader-binding.yaml # Role Binding do ConfigMap Reader
- prometheus/prometheus-adapter-deployment.yaml # Deployment do Prometheus Adapter
- prometheus/prometheus-adapter-rbac.yaml  # Role do Prometheus Adapter
- prometheus/prometheus-deployment.yaml    # Deployment do Prometheus
- prometheus/prometheus-pv.yaml            # PV do Prometheus
- prometheus/prometheus-service.yaml       # Serviço do Prometheus
- promtail/promtail-daemonset.yaml         # DaemonSet do Promtail
- promtail/promtail-rbac.yml               # Role do Promtail
- promtail/prontail-service.yaml           # Serviço do Promtail
- redis/redis-deployment.yaml              # Deployment do Redis
- redis/redis-service.yaml             # Serviço do Redis
- redis/redis-exporter-service.yaml    # Serviço do Redis Exporter
- redis/redis-exporter-deployment.yaml # Deployment do Redis Exporter
