{{- /* templates/inference-deployment.yaml */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storia.fullname" . }}-inference
  labels:
    app: inference
    env: {{ .Values.inference.environment | default "production" }}  # Adicionando a label para o ambiente
spec:
  replicas: {{ .Values.inference.replicaCount }}
  selector:
    matchLabels:
      app: inference
      env: {{ .Values.inference.environment | default "production" }}  # Selector para o ambiente
  template:
    metadata:
      labels:
        app: inference
        env: {{ .Values.inference.environment | default "production" }}  # Label do pod
    spec:
      containers:
      - name: inference
        image: "{{ .Values.inference.image.repository }}:{{ .Values.inference.image.tag }}"
        imagePullPolicy: {{ .Values.inference.image.pullPolicy }}
        command: {{ toJson .Values.inference.command }}
        ports:
        - containerPort: {{ .Values.inference.containerPort }}
        resources:
          requests:
            memory: "{{ .Values.inference.resources.requests.memory }}"
            cpu: "{{ .Values.inference.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.inference.resources.limits.memory }}"
            cpu: "{{ .Values.inference.resources.limits.cpu }}"
        volumeMounts:
          - name: storia-logs
            mountPath: {{ .Values.inference.volume.mountPath | quote }}
      volumes:
        - name: storia-logs
          hostPath:
            path: {{ .Values.inference.volume.hostPath | quote }}
            type: {{ .Values.inference.volume.type | quote }}
