serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

apiService:
  name: "api-service"
  replicaCount: 1
  environment: production  # Default para produção
  containerPort: 5000
  image:
    repository: "tailmlops/api-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  livenessProbe:
    httpGet:
      path: "/health"
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: "/health"
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 3
  volume:
    mountPath: "/var/log/storia"
    hostPath: "/var/log/storia"
    type: "DirectoryOrCreate"
  service:
    port: 8080
    type: "ClusterIP"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 80

inference:
  replicaCount: 1
  environment: production  # Default para produção
  containerPort: 6000
  image:
    repository: "tailmlops/api-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  command:
    - "python"
    - "-m"
    - "app.inference_service"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
  volume:
    mountPath: "/var/log/storia"
    hostPath: "/var/log/storia"
    type: "DirectoryOrCreate"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 80
  service:
    port: 6000
    type: "ClusterIP"

worker:
  replicaCount: 1
  initContainer:
    image: "busybox"
    command:
      - "sleep"
      - "30"
  image:
    repository: "tailmlops/api-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  command:
    - "python"
    - "-m"
    - "app.worker"
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  volume:
    mountPath: "/var/log/storia"
    hostPath: "/var/log/storia"
    type: "DirectoryOrCreate"

ingress:
  enabled: false
  tls: false
  hosts: []

# Bloco top-level usado pelo template NOTES.txt
service:
  port: 8080
  type: "ClusterIP"
