apiService:
  replicaCount: 1
  image:
    tag: "production"

inference:
  replicaCount: 1
  image:
    tag: "production"
  hpa:
    minReplicas: 1
    maxReplicas: 10
    averageUtilization: 80

worker:
  replicaCount: 1
  image:
    tag: "production"
